[build]
  command = "echo 'No build step'"
  publish = "."

[[redirects]]
  from = "/api/gold"
  to = "/.netlify/functions/proxy-gold"
  status = 200

[[redirects]]
  from = "/api/xag"
  to = "/.netlify/functions/proxy-xag"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
